# Generated by Django 2.1.7 on 2019-10-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='password',
        ),
    ]
