# Generated by Django 2.1.7 on 2019-10-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0002_remove_registrationdata_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('reg_no', models.PositiveIntegerField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.PositiveIntegerField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationData',
        ),
    ]
