# Generated by Django 2.1.7 on 2019-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0003_auto_20191003_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationdata',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationdata',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationdata',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationdata',
            name='dob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationdata',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationdata',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationdata',
            name='reg_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationdata',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
