# Generated by Django 2.1.7 on 2019-10-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0004_auto_20191003_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENTMARKSHEETDATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('dof', models.DateTimeField(max_length=100)),
                ('reg_no', models.IntegerField()),
                ('graph_theory', models.CharField(max_length=100)),
                ('autometa_theory', models.CharField(max_length=100)),
                ('data_mining', models.CharField(max_length=100)),
                ('dsp', models.CharField(max_length=100)),
                ('networking', models.CharField(max_length=100)),
                ('computer_graphics', models.CharField(max_length=100)),
                ('grade_S', models.CharField(max_length=100)),
                ('grade_A', models.CharField(max_length=100)),
                ('grade_B', models.CharField(max_length=100)),
                ('grade_C', models.CharField(max_length=100)),
                ('grade_D', models.CharField(max_length=100)),
                ('grade_E', models.CharField(max_length=100)),
                ('grade_U', models.CharField(max_length=100)),
                ('code_962', models.IntegerField()),
                ('code_302', models.IntegerField()),
                ('code_303', models.IntegerField()),
                ('code_903', models.IntegerField()),
                ('code_301', models.IntegerField()),
                ('code_304', models.IntegerField()),
                ('branch_cse', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
