# Generated by Django 2.1.7 on 2019-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0006_auto_20191005_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='degree',
            field=models.CharField(default='0000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='gender',
            field=models.CharField(default='0000000', max_length=30),
        ),
    ]
