# Generated by Django 2.1.7 on 2019-10-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0007_auto_20191005_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarksheetdata',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='studentmarksheetdata',
            name='gender',
        ),
    ]
