# Generated by Django 2.1.7 on 2019-10-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0008_auto_20191006_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='branch_cse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
