# Generated by Django 2.1.7 on 2019-10-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0009_auto_20191006_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='branch_cse',
            field=models.CharField(default='00000', max_length=100, unique=True),
        ),
    ]
