# Generated by Django 2.1.7 on 2019-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0010_auto_20191006_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarksheetdata',
            name='degree',
            field=models.CharField(default='00000', max_length=100),
        ),
        migrations.AddField(
            model_name='studentmarksheetdata',
            name='gender',
            field=models.CharField(default='00000', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='branch_cse',
            field=models.CharField(default='00000', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='username',
            field=models.CharField(default='00000', max_length=100, unique=True),
        ),
    ]
