# Generated by Django 2.1.7 on 2019-10-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0012_auto_20191006_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
