# Generated by Django 2.1.7 on 2019-10-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0013_auto_20191006_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STUDENTMARKSHEETDATA',
        ),
    ]
