# Generated by Django 2.1.7 on 2019-10-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0017_auto_20191006_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='branch_cse',
            field=models.CharField(default='', max_length=100, null=True, unique=True),
        ),
    ]
