# Generated by Django 2.1.7 on 2019-10-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0018_auto_20191006_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksheetdata',
            name='code_304',
            field=models.IntegerField(unique=True),
        ),
    ]
