# Generated by Django 2.1.7 on 2019-10-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0025_auto_20191011_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_title', models.IntegerField(choices=[(1, 'CS101'), (2, 'CS102'), (3, 'CS103'), (4, 'CS104'), (5, 'CS105'), (6, 'CS106')], default='1')),
            ],
        ),
    ]
