# Generated by Django 2.1.7 on 2019-10-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0026_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='grade_title',
            field=models.IntegerField(choices=[(1, 'grade_S'), (2, 'grade_A'), (3, 'grade_B'), (4, 'grade_C'), (5, 'grade_D'), (6, 'grade_E'), (7, 'grade_U')], default='1'),
        ),
    ]
