# Generated by Django 2.1.7 on 2019-10-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0028_auto_20191012_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='grade_title',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'U')], default='1'),
        ),
    ]
