# Generated by Django 2.1.7 on 2019-10-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0029_auto_20191012_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='code',
            name='subject_title',
            field=models.CharField(choices=[(1, 'graph_theor'), (2, 'autometa_theor'), (3, 'data_minin'), (4, 'digital signal processing'), (5, 'networking'), (6, 'computer graphic')], default='1', max_length=10),
        ),
    ]
