# Generated by Django 2.1.7 on 2019-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0031_auto_20191012_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='subject_title',
            field=models.IntegerField(choices=[(1, 'graph_theory'), (2, 'autometa_theory'), (3, 'data_mining'), (4, 'digital signal processing'), (5, 'networking'), (6, 'computer graphic')], default='1'),
        ),
    ]
