# Generated by Django 2.1.7 on 2019-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0033_code_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='branch_title',
            field=models.IntegerField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'Civil'), (4, 'mechanical'), (5, 'EI')], default='1'),
        ),
    ]
