# Generated by Django 2.1.7 on 2019-10-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0034_code_branch_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='StudentMarksheetdata2',
        ),
    ]
