# Generated by Django 2.1.7 on 2019-10-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0036_studentmarksheetdata2_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarksheetdata2',
            name='degree_of_student',
            field=models.IntegerField(choices=[(1, 'B.Tech'), (2, 'M.Tech'), (3, 'PHD')], default='1'),
        ),
    ]
